Repository haynec/OpenSCvx, pull requests merged in 2025-06, with the labels that each got.

#158 added symbolic class and example
  examples/main.py
  examples/params/brachistochrone.py
  examples/params/cinema_vp.py
  examples/params/dr_double_integrator.py
  examples/params/dr_vp.py
  examples/params/dr_vp_nodal.py
  examples/params/dr_vp_polytope.py
  examples/params/drone_racing.py
  examples/params/dubins_car.py
  examples/params/obstacle_avoidance.py
  examples/params/obstacle_avoidance_nodal.py
  examples/plotting.py
  openscvx/backend/control.py
  openscvx/backend/expr.py
  openscvx/backend/expressions.py
  openscvx/backend/parameter.py
  openscvx/backend/state.py
  openscvx/backend/utils.py
  openscvx/backend/variable.py
  openscvx/config.py
  openscvx/constraints/ctcs.py
  openscvx/ocp.py
  openscvx/post_processing.py
  openscvx/propagation.py
  openscvx/ptr.py
  openscvx/trajoptproblem.py
  tests/test_constraints/test_ctcs.py
  tests/test_examples.py
  tests/test_propagation.py
Labels: enhancement

#159 Feature/parameter update
  examples/params/dubins_car.py
  examples/plotting.py
  openscvx/augmentation/dynamics_augmentation.py
  openscvx/backend/parameter.py
  openscvx/backend/state.py
  openscvx/constraints/ctcs.py
  openscvx/constraints/violation.py
  openscvx/discretization.py
  openscvx/dynamics.py
  openscvx/propagation.py
  openscvx/ptr.py
  openscvx/trajoptproblem.py
  openscvx/utils.py
  tests/test_discretization.py
  tests/test_propagation.py
Labels: enhancement

#162 added state and control tests
  openscvx/backend/control.py
  openscvx/backend/state.py
  openscvx/trajoptproblem.py
  tests/test_variables.py
Labels: enhancement

#163 Feature/brachistochrone tests
  examples/params/dubins_car.py
  openscvx/config.py
  openscvx/ocp.py
  tests/test_examples.py
Labels: enhancement

#164 Feature/state_control_parameter_objects
  examples/main.py
  examples/params/brachistochrone.py
  examples/params/cinema_vp.py
  examples/params/dr_double_integrator.py
  examples/params/dr_vp.py
  examples/params/dr_vp_nodal.py
  examples/params/dr_vp_polytope.py
  examples/params/drone_racing.py
  examples/params/dubins_car.py
  examples/params/obstacle_avoidance.py
  examples/params/obstacle_avoidance_nodal.py
  examples/plotting.py
  openscvx/augmentation/dynamics_augmentation.py
  openscvx/backend/control.py
  openscvx/backend/expr.py
  openscvx/backend/parameter.py
  openscvx/backend/state.py
  openscvx/backend/utils.py
  openscvx/backend/variable.py
  openscvx/config.py
  openscvx/constraints/__init__.py
  openscvx/constraints/boundary.py
  openscvx/constraints/ctcs.py
  openscvx/constraints/violation.py
  openscvx/discretization.py
  openscvx/dynamics.py
  openscvx/ocp.py
  openscvx/post_processing.py
  openscvx/propagation.py
  openscvx/ptr.py
  openscvx/trajoptproblem.py
  openscvx/utils.py
  tests/test_constraints/test_boundary.py
  tests/test_constraints/test_ctcs.py
  tests/test_discretization.py
  tests/test_examples.py
  tests/test_propagation.py
  tests/test_variables.py
Labels: enhancement

#167 added animaiton plot for 3DoF
  examples/params/3DoF_pdg.py
  examples/plotting.py
Labels: enhancement

#168 added problem summary
  openscvx/_version.py
  openscvx/io.py
  openscvx/trajoptproblem.py
Labels: enhancement

#173 Feature/dev3
  examples/params/3DoF_pdg.py
  openscvx/_version.py
  openscvx/config.py
  openscvx/constraints/ctcs.py
  openscvx/io.py
  openscvx/trajoptproblem.py
  openscvx/utils.py
  tests/test_constraints/test_ctcs.py
  tests/test_ctcs_violation.py
Labels: enhancement

#176 allows for custom scaling for state and control
  openscvx/config.py
  tests/test_variables.py
Labels: enhancement

#181 Chore/reorganize examples
  examples/abstract/3DoF_pdg.py
  examples/abstract/brachistochrone.py
  examples/drone/cinema_vp.py
  examples/drone/dr_double_integrator.py
  examples/drone/dr_vp.py
  examples/drone/dr_vp_nodal.py
  examples/drone/dr_vp_polytope.py
  examples/drone/drone_racing.py
  examples/drone/obstacle_avoidance.py
  examples/drone/obstacle_avoidance_nodal.py
  examples/drone/obstacle_avoidance_realtime_test.py
  examples/dubins_car/dubins_car.py
  examples/dubins_car/dubins_car_disjoint.py
  examples/dubins_car/dubins_car_stljax.py
  examples/realtime/drone_racing_realtime.py
  examples/realtime/dubins_car_realtime.py
  examples/realtime/obstacle_avoidance_realtime.py
  tests/test_examples.py
Labels: chore

#182 Fix/release versioning issues
  .github/workflows/release.yml
Labels: bug
