Repository haynec/OpenSCvx, pull requests merged in 2025-05, with the labels that each got.

#114 Feature/draft release writer
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: patch

#118 Refactor/workflow-tweaks
  .github/release-drafter.yml
Labels: refactor

#121 Chore/readme maintenance
  .github/release-drafter.yml
  .github/workflows/ci.yml
  README.md
Labels: chore

#120 Feature/user defined nodal gradients
  openscvx/constraints/nodal.py
  openscvx/trajoptproblem.py
  tests/test_constraints/test_nodal.py
Labels: enhancement

#133 Feature/user defined ctcs and dynamics gradients
  examples/params/cinema_vp.py
  examples/params/dr_vp.py
  examples/params/dr_vp_nodal.py
  examples/params/dr_vp_polytope.py
  examples/params/drone_racing.py
  examples/params/obstacle_avoidance.py
  examples/params/obstacle_avoidance_nodal.py
  openscvx/augmentation/__init__.py
  openscvx/augmentation/ctcs.py
  openscvx/augmentation/dynamics_augmentation.py
  openscvx/constraints/ctcs.py
  openscvx/constraints/violation.py
  openscvx/discretization.py
  openscvx/dynamics.py
  openscvx/trajoptproblem.py
  tests/test_constraints/__init__.py
  tests/test_constraints/test_ctcs.py
  tests/test_ctcs_sorting.py
  tests/test_ctcs_violation.py
  tests/test_discretization.py
  tests/test_dynamics_augmentation.py
Labels: enhancement

#134 Fix/release workflow missing permissions
  .github/workflows/release.yml
Labels: bug

#135 Fix/only upload wheel from release workflow
  .github/workflows/release.yml
Labels: bug

#139 Feature/separate propagation dynamics
  openscvx/config.py
  openscvx/post_processing.py
  openscvx/trajoptproblem.py
Labels: enhancement

#141 Fix/correct changelog hyperlink
  .github/release-drafter.yml
Labels: bug

#142 Chore/update readme
  README.md
Labels: chore

#145 Documentation/dynamics
  openscvx/dynamics.py
Labels: documentation

#147 Documentation/integrators
  openscvx/constraints/ctcs.py
  openscvx/constraints/nodal.py
  openscvx/integrators.py
Labels: documentation

#148 Chore/double integrator example
  examples/params/dr_double_integrator.py
  examples/plotting.py
Labels: chore

#149 removed unneccesary jits
  openscvx/trajoptproblem.py
  tests/test_examples.py
Labels: refactor

#150 bndry conditions are now passed in as parameters
  openscvx/ocp.py
  openscvx/ptr.py
Labels: enhancement

#153 allows initial time to be non-zero
  openscvx/post_processing.py
  openscvx/propagation.py
  tests/test_propagation.py
Labels: enhancement

#154 removed shape polymorphism
  openscvx/integrators.py
  openscvx/propagation.py
  openscvx/trajoptproblem.py
  tests/test_integrators.py
  tests/test_propagation.py
Labels: refactor

#155 Refactor/static shape propagation
  openscvx/config.py
  openscvx/integrators.py
  openscvx/propagation.py
  openscvx/trajoptproblem.py
  tests/test_integrators.py
  tests/test_propagation.py
Labels: refactor
